### ISSUE TITLE
Status not correctly pulling from ZAP

### ISSUE THREAD

**Issue by matthewpietrus** [NYCPlanning/dcp-zap-data-feedback#145]
Status in ZAP shows approved (P2011M0070) but ZAP Search shows as in public review.

**Comment by SomeCityBureaucrat** [comment]
Mathew, I've alerted the Planning Labs team to the issue.  I noticed my changes were not appearing.  Chris says he's looking into it.  I'll leave this as an active issue to remind me to follow up.

**Comment by SomeCityBureaucrat** [comment]
This was fixed.
