### ISSUE TITLE
Feedback about 243 Howard Avenue

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/dcp-zap-data-feedback#15]
Project ID: [P2014R0356](https://zap.planning.nyc.gov/projects/P2014R0356)
Feedback: This project includes Land Use Application Milestones that do not have dates, causing a rendering error in the frontend.

**Comment by SomeCityBureaucrat** [comment]
I e-mailed the planner with the suggested solution - either deactivate the milestones or activate them and backdate them with the help of the BCM.

**Comment by SomeCityBureaucrat** [comment]
This has been fixed.
