### ISSUE TITLE
Data quality issue around Brooklyn CB 1

### ISSUE THREAD

**Issue by noneck** [NYCPlanning/dcp-zap-data-feedback#22]
![screen shot 2018-07-14 at 13 28 53](https://user-images.githubusercontent.com/94735/42726886-1acde498-876a-11e8-9051-c8af571c057c.png)

Under completed projects in Brooklyn Community Board 1, I see a few lots that are not in CB 1.

**Comment by SomeCityBureaucrat** [comment]
Thanks, this is a known issue that the geography filters have made easier to see.  The dots are the center points of projects with multiple geographies and may in fact be correct - an example would be a bulk disposition action that includes lots all over the borough.  That said there are mistakes.  I will correct them and record them here. 
WILLIAMSBURG BRANCH PUBLIC LIBRARY - has the wrong BBL 1021890001.  I changed the BBL to 3021890001 it should show up in a few hours (7/31/2018 10:50 AM)

PS11 & POILLON-SEGUINE BRITTON HSE - this is a multiple geography project (bulk landmarking) working on it now...

**Comment by SomeCityBureaucrat** [comment]
PS11 & POILLON-SEGUINE BRITTON HSE - this is a multiple geography project (bulk landmarking) the BBLs have been entered for this - the dot will not show up in BK 1 but it will reflect the center point of all the sites.

118 Withers St. - this has an incorrect lot in the Bronx entered.  I have deactivated those and will see what that does.

To be continued

**Comment by SomeCityBureaucrat** [comment]
Hubbard House - this is a landmark designation in CD 11 in Brooklyn, there was a typo and I fixed it (8/2/2018)

COP (C890457 PPK) - this is a disposition of City-owned-property in CD 18, there was a typo and I fixed it (8/2/2018)

COP (C 861007 PPK thu C861010 PPK) - this is a disposition of 147 properties in multiple community districts.  This will require a bulk up load of BBLs to reflect the project record accurately.  TBC

WASTE MANAGEMENT CORP - this is a disposition at 92 Grattan Street, it was incorrectly entered as 92 Grafton Street.  This has been corrected.

Williamsburg II Urban Renewal Plan Amendment - is entered as a separate issue, this will require a bulk upload.  TBC

Other than the projects requiring bulk uploads this appears to now be resolved.

**Comment by SomeCityBureaucrat** [comment]
Further update: Hubbard House and COP (C890457 PPK) did not correct.  there was a lot incorrectly associated with them from CD 1.  I changed the lot and deactivated it.  We'll see if that corrects the issue.

**Comment by SomeCityBureaucrat** [comment]
Leaving this open as there is one last project with incorrect data - it is a disposition of City-owned property with 147 separate lots.  I am working on a bulk upload protocol and it will take time.

**Comment by SomeCityBureaucrat** [comment]
These have all been corrected now.
