### ISSUE TITLE
Feedback about 605 Hart Street FRESH (Authorization)

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/dcp-zap-data-feedback#40]
Project ID: [P2016K0120](https://zap.planning.nyc.gov/projects/P2016K0120)
Feedback: Milestones are out of order - possible data issue?

**Comment by SomeCityBureaucrat** [comment]
I think there is an issue with ad-hoc milestones being out of order.  We've seen it on other projects.  How does Search order the milestones?  It appears to be in an order set by ZAP and not by date of completion.

**Comment by SomeCityBureaucrat** [comment]
This specific instance has been corrected.
