### ISSUE TITLE
Feedback about KING AVE & KILROE/ELIZABETH ST

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/dcp-zap-data-feedback#41]
Project ID: [P1979X0070](https://zap.planning.nyc.gov/projects/P1979X0070)
Feedback: For all projects, there shouldn't be a link to files with no CPC report.

**Comment by SomeCityBureaucrat** [comment]
This is a known issue and not really a data issue  please see issue 397 in https://github.com/NYCPlanning/labs-zap-search/issues going forward.
