### ISSUE TITLE
Feedback about KALIEN COMMONS

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/dcp-zap-data-feedback#42]
Project ID: [P1999R0233](https://zap.planning.nyc.gov/projects/P1999R0233)
Feedback: This is an old application from the 1990's and the project info is missing. 

More importantly, the later ULURP applications #030449 for a rezoning approved in 2004 (and the other associated zoning applications for S. Richmond actions) are not identified on the map at all.

**Comment by SomeCityBureaucrat** [comment]
This is a school seat certification.  There isn't much in the way of milestones to show.  I agree it would be useful to identify the action so people know.  The rezoning should have a geography- that we can work on.
